w4d2/ninetyninecats/config/routes.rb
Rails.application.routes.draw do

  resources :cats, only: [:index, :show, :new, :create, :update, :edit]
  resources :cat_rental_requests, only: [:index, :show, :new, :create, :update, :edit]
  root to: 'cats#indexs'
end

w4d2/ninetyninecats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  birth_date  :date             not null
#  age         :integer          not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  color       :string           not null
#

class Cat < ActiveRecord::Base
  validates :name, :birth_date, :age, :sex, :color, presence: true
  validates :color, inclusion: { in: %w(black brown white tan yellow orange green),
    message: "%{value} is not a valid color" }
  validates :sex, inclusion: { in: %w(M F), message: "Sex can only be M or F"}

  def calc_age
    ((Date.today - self.birth_date) / 365).to_i
  end

  has_many :cat_rental_requests, :dependent => :destroy
end

w4d2/ninetyninecats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           not null
#  created_at :datetime
#  updated_at :datetime
#

class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion:   { in: %w(PENDING APPROVED DENIED) }
  validate :no_overlapping_approved_requests_for_cat

  def overlapping_requests
    start = self.start_date
    finish = self.end_date
    CatRentalRequest.where("start_date BETWEEN(#{start} AND #{finish})
      OR end_date BETWEEN(#{start} AND #{finish})")
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def no_overlapping_approved_requests_for_cat
    if overlapping_approved_requests.exists?(cat_id: self.cat_id)
      errors[:cat_id] << "cat is already rented during that time"
    end
  end

  belongs_to :cat
end

w4d2/ninetyninecats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

w4d2/ninetyninecats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cats = Cat.all
    render :new
  end

  def create
    
  end
end

w4d2/ninetyninecats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.age = @cat.calc_age

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])

    if @cat.persisted?
      render :edit
    else
      redirect_to :new
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :birth_date, :sex, :color, :description)
  end
end

w4d2/ninetyninecats/app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

w4d2/ninetyninecats/app/helpers/cats_helper.rb
module CatsHelper
end

w4d2/ninetyninecats/app/views/cat_rental_requests/new.html.erb
<h1>Enter Rental Request:</h1>

<form action="cat_rental_requests_url" method="post">
  <label for="cat_name">Cat Name: </label>
  <select name="cat_rental_request[cat_id]">
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"> <%= cat.name %> </option>
    <% end %>
  </select>

  <br>
  <label for="start_date">Start Date: </label>
  <input type="date" name="cat_rental_request[start_date]">

  <br>
  <label for="end_date">End Date: </label>
  <input type="date" name="cat_rental_request[end_date]">

  <br>
  <input type="submit" value="Submit Request">

</form>

w4d2/ninetyninecats/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = edit_cat_url %>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form  action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name:</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">
  <br>
  <br>
  <label for="sex">Sex:</label>
  <input type="radio" name="cat[sex]" value="M" <%= 'checked' if cat.sex == 'M' %> > M
  <input type="radio" name="cat[sex]" value="F" <%= 'checked' if cat.sex == 'F' %> > F
  <br>
  <br>
  <label for="color">Color:</label>
  <select name="cat[color]">
    <option value="--choose color--" disabled selected>--Choose Color--</option>
    <option value="black" <%= 'selected' if cat.color = 'black' %> >black</option>
    <option value="brown" <%= 'selected' if cat.color = 'brown' %> >brown</option>
    <option value="white" <%= 'selected' if cat.color = 'white' %> >white</option>
    <option value="tan" <%= 'selected' if cat.color = 'tan' %> >tan</option>
    <option value="yellow" <%= 'selected' if cat.color = 'yellow' %> >yellow</option>
    <option value="orange" <%= 'selected' if cat.color = 'orange' %> >orange</option>
    <option value="green" <%= 'selected' if cat.color = 'green' %> >green</option>
  </select>
  <br>
  <br>
  <label for="birth_date">Birth Date:</label>
  <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  <br>
  <br>
  <label for="description">Description:</label>
  <textarea name="cat[description]"> <%= cat.description %> </textarea>
  <br>
  <input type="submit" value="Submit Request">
</form>

w4d2/ninetyninecats/app/views/cats/edit.html.erb
<h1>Enter Revision to Cat Below:</h1>

<%= render 'form', action: :edit, cat: @cat %>

w4d2/ninetyninecats/app/views/cats/index.html.erb
<h1>All the Cats!</h1>

<body>
  <ul>
    <% @cats.each do |cat| %>
      <li> <a href="http://localhost:3000/cats/<%=cat.id%>"> <%= cat.name %> </li>
    <% end %>
  </ul>
</body>

w4d2/ninetyninecats/app/views/cats/new.html.erb
<h1>Enter New Cat's Information Below:</h1>

<%= render 'form', action: :new, cat: @cat %>

w4d2/ninetyninecats/app/views/cats/show.html.erb
<h1> Here Lies <%= @cat.name %>! </h1>

  <h2>Info for <%= @cat.name %>: </h2>

  <table border="1">
    <colgroup span ="5"></colgroup>
    <tr>
      <th>Birth Date</th>
      <th>Age</th>
      <th>Color</th>
      <th>Sex</th>
      <th>Description</th>
    </tr>
    <tr>
      <td> <%= @cat.birth_date %> </td>
      <td> <%= @cat.age %> </td>
      <td> <%= @cat.color %> </td>
      <td> <%= @cat.sex %> </td>
      <td> <%= @cat.description %> </td>
    </tr>
  </table>